- abs.yaml
- recipe/0001-add-python-3.8-bazel-dependency.patch
- recipe/build.sh
- recipe/fix-conda-version.patch
- recipe/meta.yaml
> update to 1.0.6

- abs.yaml
- recipe/meta.yaml
- update to 1.0.10
- [requirements](https://github.com/snowflakedb/snowflake-ml-python/blob/1.0.10/requirements.yml)
- removed training_dataset test as the directory is no longer there [training_dataset](https://github.com/snowflakedb/snowflake-ml-python/tree/1.0.9/snowflake/ml/training_dataset) in 1.0.10
> update to 1.0.10

- recipe/meta.yaml
update to 1.0.12
- [requirements](https://github.com/snowflakedb/snowflake-ml-python/blob/1.0.12/requirements.yml)
> update to 1.0.12

- recipe/meta.yaml
snowflake-ml-python 1.2.3
- [PKG-4164]
- [Upstream repository](https://github.com/snowflakedb/snowpark-python/)
- [Upstream changelog/diff](https://github.com/snowflakedb/snowflake-ml-python/compare/1.2.2...1.2.3)
- dependencies have been reordered to match order in [requirements.yml](https://github.com/snowflakedb/snowflake-ml-python/blob/1.2.3/requirements.yml)
[PKG-4164]: https://anaconda.atlassian.net/browse/PKG-4164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build 1.2.3

- abs.yaml
- recipe/meta.yaml
snowflake-ml-python 1.3.0 ❄️ 
- [PKG-4273]
- [Upstream repository](https://github.com/snowflakedb/snowflake-ml-python/tree/1.3.0)
- [Upstream changelog/diff](https://github.com/snowflakedb/snowflake-ml-python/compare/1.2.3..1.3.0)
[PKG-4273]: https://anaconda.atlassian.net/browse/PKG-4273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> build 1.3.0

- recipe/meta.yaml
snowflake-ml-python  1.4.0
**Destination channel:** defaults
- [PKG-4423] 
- [Upstream repository](https://github.com/snowflakedb/snowflake-ml-python/tree/1.4.0)
- [Upstream changelog/diff](https://github.com/snowflakedb/snowflake-ml-python/compare/1.3.0..1.4.0)
[PKG-4423]: https://anaconda.atlassian.net/browse/PKG-4423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> update to 1.4.0

- recipe/bld.bat
- recipe/meta.yaml
snowflake-ml-python
defaults
- [PKG-4652](https://anaconda.atlassian.net/browse/PKG-4652) 
- [upstream](https://github.com/snowflakedb/snowflake-ml-python/tree/1.5.0)
[PKG-4652]: https://anaconda.atlassian.net/browse/PKG-4652?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.5.0

- recipe/meta.yaml
snowflake-ml-python 1.6.1 
- [PKG-5513]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.6.1
- conda_forge:    https://github.com/conda-forge/snowflake-ml-python-feedstock/blob/main/recipe/meta.yaml
- pypi:           https://pypi.org/project/snowflake-ml-python/1.6.1
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.6.1
- updated to 1.6.1
[PKG-5513]: https://anaconda.atlassian.net/browse/PKG-5513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.6.1 

- recipe/meta.yaml
snowflake-ml-python 1.7.1 
- [PKG-6091]
- [dev_url](https://github.com/snowflakedb/snowflake-ml-python/tree/1.7.1)
- [conda_forge](https://github.com/conda-forge/snowflake-ml-python-feedstock/blob/main/recipe/meta.yaml)
- [pypi](https://pypi.org/project/snowflake-ml-python/1.7.1)
- [pypi inspector](https://inspector.pypi.io/project/snowflake-ml-python/1.7.1)
- [Upstream diff](https://github.com/snowflakedb/snowflake-ml-python/compare/1.7.0...1.7.1#diff-4db974eadd3011661a082fa9471f344e2086c3005084558cbcaf337e39eec304) 
- New version number
- Reflected upstream diff
[PKG-6091]: https://anaconda.atlassian.net/browse/PKG-6091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.7.1 

- recipe/meta.yaml
snowflake-ml-python 1.7.2 
- [PKG-6270]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.7.2
- conda_forge:    https://github.com/conda-forge/snowflake-ml-python-feedstock/blob/main/recipe/meta.yaml
- pypi:           https://pypi.org/project/snowflake-ml-python/1.7.2
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.7.2
[PKG-6270]: https://anaconda.atlassian.net/browse/PKG-6270?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.7.2 

- recipe/meta.yaml
snowflake-ml-python 1.7.3 
- [PKG-6737]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.7.2
- conda_forge:    https://github.com/conda-forge/snowflake-ml-python-feedstock/blob/main/recipe/meta.yaml
- pypi:           https://pypi.org/project/snowflake-ml-python/1.7.2
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.7.2
- dependency updates
[PKG-6737]: https://anaconda.atlassian.net/browse/PKG-6737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.7.3 

- recipe/meta.yaml
snowflake-ml-python 1.7.4
**Destination channel:** Default
- [PKG-6935](https://anaconda.atlassian.net/browse/PKG-6935) 
- [source code](https://github.com/snowflakedb/snowflake-ml-python/tree/1.7.4)
- [PyPi](https://pypi.org/project/snowflake-ml-python/1.7.4)
- [conda-forge](https://github.com/conda-forge/snowflake-ml-python-feedstock)
[PKG-6935]: https://anaconda.atlassian.net/browse/PKG-6935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> PKG-6935: snowflake-ml-python 1.7.4

- recipe/meta.yaml
snowflake-ml-python 1.8.0 
- [PKG-7490]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.7.4
- pypi:           https://pypi.org/project/snowflake-ml-python/1.7.4
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.7.4
[PKG-7490]: https://anaconda.atlassian.net/browse/PKG-7490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.8.0 

- abs.yaml
- recipe/meta.yaml
snowflake-ml-python 1.8.1 
- [PKG-7637]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.8.1
- pypi:           https://pypi.org/project/snowflake-ml-python/1.8.1
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.8.1
[PKG-7637]: https://anaconda.atlassian.net/browse/PKG-7637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.8.1 

- recipe/meta.yaml
snowflake-ml-python 1.8.2 
- [PKG-8079]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.8.1
- pypi:           https://pypi.org/project/snowflake-ml-python/1.8.1
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.8.1
[PKG-8079]: https://anaconda.atlassian.net/browse/PKG-8079?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.8.2 

- recipe/meta.yaml
snowflake-ml-python 1.8.3 
- [PKG-8073]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.8.1
- pypi:           https://pypi.org/project/snowflake-ml-python/1.8.1
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.8.1
[PKG-8073]: https://anaconda.atlassian.net/browse/PKG-8073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.8.3 

- recipe/meta.yaml
snowflake-ml-python 1.9.0 
- [PKG-8618]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.9.0
- pypi:           https://pypi.org/project/snowflake-ml-python/1.9.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.9.0
[PKG-8618]: https://anaconda.atlassian.net/browse/PKG-8618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.9.0 

- recipe/meta.yaml
snowflake-ml-python 1.11.0 
- [PKG-9170]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.11.0
- pypi:           https://pypi.org/project/snowflake-ml-python/1.11.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.11.0
[PKG-9170]: https://anaconda.atlassian.net/browse/PKG-9170?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.11.0 

- recipe/meta.yaml
snowflake-ml-python 1.12.0 
- [PKG-9546]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.12.0
- pypi:           https://pypi.org/project/snowflake-ml-python/1.12.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.12.0
[PKG-9546]: https://anaconda.atlassian.net/browse/PKG-9546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.12.0 

- recipe/meta.yaml
snowflake-ml-python 1.14.0 
- [PKG-9814]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.14.0
- pypi:           https://pypi.org/project/snowflake-ml-python/1.14.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.14.0
[PKG-9814]: https://anaconda.atlassian.net/browse/PKG-9814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.14.0 

- recipe/meta.yaml
snowflake-ml-python 1.16.0 
- [PKG-10058]
- dev_url:        https://github.com/snowflakedb/snowflake-ml-python/tree/1.16.0
- pypi:           https://pypi.org/project/snowflake-ml-python/1.16.0
- pypi inspector: https://inspector.pypi.io/project/snowflake-ml-python/1.16.0
[PKG-10058]: https://anaconda.atlassian.net/browse/PKG-10058?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> snowflake-ml-python 1.16.0 
